config/routes.rb
Rails.application.routes.draw do
  get 'subscriptions/subscribe/:id', to: "subscriptions#subscribe", as: "subscribe"

  get 'subscriptions/unsubscribe/:id', to: "subscriptions#unsubscribe", as: "unsubscribe"

  devise_for :users
  resources :courses
  

  root  'courses#index'
  

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :users
    validates :name, presence: true
    belongs_to :owner,  class_name: "User"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :courses
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def index
 	# need to put the right folder also, use quotes
 	@courses = Course.all
 end

 def show
 	@course = Course.find(params[:id])
 	
 end
 
 def create
    @course =  Course.create(course_params.merge(owner_id: current_user.id))
    if @course.save
      redirect_to root_path
    else
      #render :action => 'new'
    end
  end

  def new
  	 @course = Course.new

  end

 def edit
    @course = Course.find params[:id]
  end

def update
    @course = Course.find params[:id]
    if @course.update_attributes(course_params)
      redirect_to course_path
    else
      render :action => :edit
    end
  end

private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def course_params
      params.require(:course).permit(:name, :description)
      
    end



end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def subscribe
  	@course = Course.find(params[:id])
  	current_user.courses << @course
  	redirect_to course_path
  end
  

  def unsubscribe
  	@course = Course.find(params[:id])
  	current_user.courses.delete(@course)
  	redirect_to course_path  
  end

 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connector_helper.rb
module ConnectorHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |form| %>
  <%= form.label :name %> </br>
  <%= form.text_field :name %></br>
  <%= form.label :description %> </br>
  <%= form.text_area :description %></br>
  <%= form.submit %>
<% end -%>

app/views/courses/edit.html.erb
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete,  class: 'navbar-link'  %>
   </p>
  <p><%= link_to 'Create Course', new_course_path, :class => 'navbar-link' %> |</p>

<% @courses.each do |course| %>
    <li>
        <%= link_to course.name, course %>
        
<% end %>


<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

<% end %>

app/views/courses/new.html.erb
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>

<p><%= @course.description %></p> 

By:
<p><%= @course.owner.email %></p>


<% if current_user.id == @course.owner_id %>
        <%= link_to 'Edit Course', edit_course_path, :class => 'navbar-link' %>  
<% else %>
		<% if current_user.courses.include?(@course) %>
		<%= link_to 'Unsubscribe Course', unsubscribe_path, :class => 'navbar-link' %>
		<% else %>
        <%= link_to 'Subscribe Course', subscribe_path, :class => 'navbar-link' %>
        <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Udemi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>








<%= yield %>

</body>
</html>

app/views/subscription/create.html.erb
<h1>Subscription#create</h1>
<p>Find me in app/views/subscription/create.html.erb</p>

app/views/subscription/destroy.html.erb
<h1>Subscription#destroy</h1>
<p>Find me in app/views/subscription/destroy.html.erb</p>